### ISSUE TITLE
Fixing UI

### ISSUE THREAD

**Issue by picvet** [ThembaMahlangu/restaurant-orders#1]
I am working on your UI. I feel like some of the things could change such as the colors and some work arounds on the responsiveness of the screen. I'll be making a few pull requests on this project.

**Comment by ThembaMahlangu** [comment]
Kwazi can you send a couple of screenshots from your different point of views so that i can understand what you mean and see where you can contribute. I made this project open-source so that I give others a chance to have something beautiful and using the latest technology. Please note that I am using TailwindCSS for styling the web app so anything you do maintain the usage of the framework

**Comment by picvet** [comment]
I'll share some screen shots soon. Still working on it but here's the progress so far.

![image](https://github.com/ThembaMahlangu/restaurant-orders/assets/87276390/d8cafb6a-6104-47e3-94bc-5acb632abaeb)

1. I felt like making the navbar white was not going well for the design. 

My idea for colors:
- Gray: Would be the primary color ( so this will be used in most of the things that don't require attention )
- White: Secondary ( so text and other form of content could be this color )
- Red: Call to action color so whatever clickable you have on the design you could use this color.

2. Another issue was the social media links they were also white and the background was also white so they didn't show up.

I tried debugging this for about 10 mins without realizing you had these social media on the navbar which is another reason for changing the navbar color.


If you don't like what I've done so far that's okay I won't make a pull request

**Comment by ThembaMahlangu** [comment]
That's actually nice, we'll stick with it. I'm still busy with adding more
components and then I'll move to adding the necessary pages

**Comment by ThembaMahlangu** [comment]
Can you also take a screenshot for mobile when the hamburger menu is open
and when closed

**Comment by picvet** [comment]
Awesome stuff. 

I'm still trying to work on the mobile hamburger to make it look better for now it is still your default.

![image](https://github.com/ThembaMahlangu/restaurant-orders/assets/87276390/2224d07a-a87b-4ea6-aa57-1ddf5b16c080)


Which is this image on top

**Comment by ThembaMahlangu** [comment]
Awesome you can also edit the Navbar by adding the social media icons on it
under the Logo/Title

**Comment by picvet** [comment]
I think I could make it look better though the hamburger menu. I'm making a pull request for the fixed bg for navbar then I'll work on the hamburger menu next

**Comment by ThembaMahlangu** [comment]
Only do the pull request once you done with everything, then you can focus on the components i'll add too

**Comment by picvet** [comment]
Let me check out other peoples designs of hamburger then I'll send the design here probably at night cause I have to go somewhere soon.

Cool. I'll just make a pull request when done with the navbar.

**Comment by picvet** [comment]
You should probably create a log for this web application.

**Comment by ThembaMahlangu** [comment]
What do you mean when you say a log. Explain the feature in detail

**Comment by picvet** [comment]
Sorry that's a typo I meant logo

**Comment by ThembaMahlangu** [comment]
Nah I don't need the logo, I'm going to only put a logo if I get a customer
who wants the site. But I'm gonna tweak it a bit so it doesn't look exactly
as what we building
